# Generated by Django 5.0.6 on 2024-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='senha',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='Usa@2024', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
