# Generated by Django 5.0.7 on 2024-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['modelo'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='termo',
            options={'ordering': ['dt_inicio'], 'verbose_name': 'Termo', 'verbose_name_plural': 'Termos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='termo',
            name='dt_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='termo',
            name='dt_inicio',
            field=models.DateField(),
        ),
    ]
