# Generated by Django 5.0.7 on 2024-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0003_equipamento_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='descricao',
            field=models.CharField(blank=True, max_length=244),
        ),
    ]
