# Generated by Django 5.1 on 2024-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0005_alter_equipamento_maq_alter_equipamento_patrimonio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='dt_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
