# Generated by Django 5.0.6 on 2024-11-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0007_alter_equipamento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termo',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='termo',
            name='equipamento',
            field=models.ManyToManyField(to='termo.equipamento'),
        ),
    ]
