# Generated by Django 5.0.6 on 2024-11-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0008_remove_termo_equipamento_termo_equipamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termo',
            old_name='equipamento',
            new_name='equipamentos',
        ),
    ]
