# Generated by Django 5.0.6 on 2024-11-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0009_rename_equipamento_termo_equipamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termo',
            name='equipamentos',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='termo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='termo.termo'),
        ),
    ]
