# Generated by Django 5.0.6 on 2024-11-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo', '0010_remove_termo_equipamentos_equipamento_termo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='termo',
        ),
        migrations.AddField(
            model_name='termo',
            name='equipamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='termo.equipamento'),
        ),
    ]
